version: '3.6'
services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    restart: always
    networks:
      - internal
    volumes:
      - ./db:/data
  worker:
    image: lolpants/dreddit
    build: '.'
    depends_on:
      - redis
    networks:
      - internal
    volumes:
      - ./config/config.json:/usr/app/config/config.json
networks:
  internal:
