name: Docker Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
          IMAGE_NAME=dreddit

          GIT_REPO='https://github.com/${{ github.repository }}'
          DOCKER_USER=`echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]'`
          DOCKER_IMAGE=ghcr.io/$DOCKER_USER/$IMAGE_NAME

          VERSION=`git rev-parse --short HEAD`
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi

          echo ::set-output name=git_repo::${GIT_REPO}
          echo ::set-output name=docker_user::${DOCKER_USER}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=version::${VERSION}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ steps.prepare.outputs.docker_user }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ (github.ref == 'refs/heads/master') || (contains(github.ref, 'refs/tags/') == true) }}
          tags: ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}
          build-args: GIT_REPO=${{ steps.prepare.outputs.git_repo }}
          # platforms: linux/amd64,linux/arm64
